### ISSUE TITLE
Use r2d2

### ISSUE THREAD

**Issue by gwenn** [gsquire/yaus#1]
> The binary uses a Mutex to wrap the SQLite connection. I know Iron offers a crate called persistent which lets you avoid this. However it is only for types that implement both Send and Sync and SQLite's Connection type does not. This is unfortunate in that it makes the endpoints blocking.
> 
> If I am missing something obvious, please open a pull request or issue to fix this. I tried to avoid a Mutex but I think it is the only way to avoid reopening the connection every time it is needed.

It seems possible to use `r2d2` with `iron` (https://github.com/superlogical/rustwebapp)

**Comment by gwenn** [comment]
You should update the README since you do already use `r2d2` !

**Comment by gsquire** [comment]
I did update a while back and forgot to change the README. I will do that! Thanks for opening this issue.
