### ISSUE TITLE
Redundant indexes

### ISSUE THREAD

**Issue by gwenn** [gsquire/yaus#2]
https://github.com/gsquire/yaus/blob/master/migrations/up.sql#L8

https://www.sqlite.org/lang_createtable.html#uniqueconst

> In most cases, UNIQUE and PRIMARY KEY constraints are implemented by creating a unique index in the database.

Since `url` and `locator` are declared unique, there is no need to create another index.

**Comment by gsquire** [comment]
Fair point. I will remove those :)
