### ISSUE TITLE
Wrong syntax for bind parameters

### ISSUE THREAD

**Issue by gwenn** [gsquire/yaus#3]
https://github.com/gsquire/yaus/blob/master/src/main.rs#L63

``` rust
    db.execute("INSERT INTO urls VALUES (NULL, $1, $2, $3)",
```

http://sqlite.org/lang_expr.html#varparam

> A dollar-sign followed by an identifier name also holds a spot for a named parameter with the name $AAAA.

Actually, it works because the order of parameter values match the order of bind parameters but it's not the correct syntax:

``` rust
    db.execute("INSERT INTO urls VALUES (NULL, ?1, ?2, ?3)",
```

**Comment by gsquire** [comment]
Good catch, I misread the SQLite docs for the crate. I will update this.
