### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [gsquire/yaus#5]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by gsquire** [comment]
I only use that crate for hex encoding I believe so I can transition away from it soon. Thanks for the reminder.

**Comment by gsquire** [comment]
Closing as this is deprecated.
